#!/usr/bin/env python3
import json
import os
import pandas as pd
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).resolve().parent.parent))
import utils


# ------------------------------
# MAIN QC FUNCTION
# ------------------------------
def run(config, subject, session):
    """
    Executes quality control (QC) checks on XCP-D outputs for a given subject and session.
    This function performs the following steps:
    - Sets up output directories for QC results.
    - Locates the XCP-D output directory for the specified subject and session.
    - Extracts processing status and runtime information from logs.
    - Counts the number of directories and files generated by XCP-D.
    - Loads the XCP-D QC metrics file (TSV format) and extracts key metrics such as mean framewise displacement (FD),
      percentage of censored frames, number of retained volumes, and mean DVARS.
    - Applies pass/fail logic based on predefined thresholds for motion and data retention, recording reasons for any failure.
    - Augments the QC metrics DataFrame with additional information (processing status, runtime, counts, fail reasons).
    - Saves the updated QC metrics to a CSV file in the QC output directory.
    - Handles and reports errors gracefully if any step fails.
    config : dict or SimpleNamespace
        Configuration object containing paths and settings, including the derivatives directory.
    subject : str
        Subject identifier (e.g., 'sub-01').
    session : str
        Session identifier (e.g., 'ses-01').
    Raises
    ------
    FileNotFoundError
        If the required XCP-D QC metrics file is not found.
    Exception
        For any other errors encountered during processing, with error details printed to stdout.
    Outputs
    -------
    - Saves an updated QC metrics CSV file in the derivatives QC directory.
    - Prints status messages and error notifications to stdout.
    """
    
    DERIVATIVES_DIR = config["common"]["derivatives"]
    xcpd_dir = f"{DERIVATIVES_DIR}/xcpd/outputs/{subject}/{session}"

    # Read bids_filter file to get the list of tasks to consider
    bids_filter_path = Path(__file__).resolve().parent / "rsfmri" / "bids_filters" / f"bids_filter_{session}.json"
    if not bids_filter_path.is_file():
        raise FileNotFoundError(f"BIDS filter file {bids_filter_path} not found.")
    with open(bids_filter_path, 'r') as f:
        bids_filter_content = json.load(f)
    tasks = bids_filter_content["bold"]["task"]
    # Convert a single string into a list
    if isinstance(tasks, str):
        tasks = [tasks]

    for task in tasks:
        try:
            # Extract process status from log files
            finished_status, runtime = utils.read_log(config, subject, session, runtype="xcpd")
            dir_count = utils.count_dirs(xcpd_dir)
            file_count = utils.count_files(xcpd_dir)

            # Load TSV file produced by XCP-D
            xcpd_metrics = f'{subject}_{session}_task-{task}_motion.tsv'
            df = pd.read_csv(os.path.join(xcpd_dir, 'func', xcpd_metrics), sep='\t')

            max_framewise_displacement = df['framewise_displacement'].max()
            max_rot_x = df['rot_x'].max()
            max_rot_y = df['rot_y'].max()
            max_rot_z = df['rot_z'].max()
            max_trans_x = df['trans_x'].max()
            max_trans_y = df['trans_y'].max()
            max_trans_z = df['trans_z'].max()
            max_rmsd = df['rmsd'].max()

            row = dict(
                subject=subject,
                session=session,
                Process_Run="xcpd",
                Finished_without_error=finished_status,
                Processing_time_hours=runtime,
                Number_of_folders_generated=dir_count,
                Number_of_files_generated=file_count,
                max_framewise_displacement=max_framewise_displacement,
                max_rot_x=max_rot_x,
                max_rot_y=max_rot_y,
                max_rot_z=max_rot_z,
                max_trans_x=max_trans_x,
                max_trans_y=max_trans_y,
                max_trans_z=max_trans_z,
                max_rmsd=max_rmsd,
            )

            # Save the updated qc_df
            sub_ses_qc = pd.DataFrame([row])
            path_to_qc = f"{DERIVATIVES_DIR}/qc/xcpd/outputs/{subject}/{session}/{subject}_{session}_task-{task}_qc.csv"
            sub_ses_qc.to_csv(path_to_qc, mode='w', header=True, index=False)
            print(f"QC saved in {path_to_qc}\n")

            print(f"XCP-D Quality Check terminated successfully for {subject} {session} task-{task}.")

        except Exception as e:
            print(f"⚠️ ERROR: QC aborted for {subject} {session} task-{task}: \n{e}")


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 4:
        raise RuntimeError(
            "Usage: python qc_xcpd_metrics_extractions.py <config> <subject> <session>"
        )
    config = json.loads(sys.argv[1])
    subject = sys.argv[2]
    session = sys.argv[3]
    run(config, subject, session)
